### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by nagayev** [embeddedmz/16-Games#1]
Hello. Is this repository official?

**Comment by embeddedmz** [comment]
Hi @nagayev 

There's no official repo for 16-Games since "FamTrinli" provided the source code (without build files) in a zip folder. I have already provided a link to this repo in the SFML forum's post created by "FamTrinli".

Unlike the other non-official forks of this project, the one I created makes use of CMake which is great to build the games with less hassles.

Github didn't notify me via email about the issues you have posted and the pull request (very strange ! - UPDATE : I found the reason)

**Comment by nagayev** [comment]
@embeddedmz Okey, thank you for your response.
